version: "2"
services:
  client:
    build:
      context: ./client
    command: yarn run start
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
  server:
    build:
      context: ./server
    command: yarn run watch
    ports:
      - "3100:3100"
    volumes:
      - ./server:/server
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    driver: "local"